services:

  db:
    image: postgres:15
    container_name: transitops_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - transitops_db_data:/var/lib/postgresql/data
    networks:
      - transitops_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:17
    container_name: transitops_odoo
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      HOST: db
      PORT: 5432
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./transitops:/mnt/extra-addons/transitops
      - transitops_odoo_data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
    networks:
      - transitops_net
    command: odoo --config=/etc/odoo/odoo.conf

volumes:
  transitops_db_data:
  transitops_odoo_data:

networks:
  transitops_net:
    driver: bridge
